baseClass: "com.paypal.selion.testcomponents.BasicPageImpl"
defaultLocale: "US"
platform: "mobile"
elements:
  settingsTitleLabel:
    ios:
        US: "//XCUIElementTypeOther[@name='Settings']"
    android:
        US: ""
  iosBackToSettingButton:
    ios:
      US: "//XCUIElementTypeButton[@name='Settings']"
    android:
      US: ""
  iosBackToMoreButton:
    ios:
      US: "//XCUIElementTypeButton[@name='More']"
    android:
      US: ""
  androidMoreOptionButton:
    ios:
      US: ""
    android:
      US: "//android.widget.ImageView[@content-desc='More options']"
  logOutButton:
    ios:
      US: "//XCUIElementTypeStaticText[@name='Log Out']"
    android:
      US: "settings_account_logout_item"
  accountButton:
    ios:
      US: "//XCUIElementTypeStaticText[@name='Account']"
    android:
      US: "settings_account_item"
  dataSourcesButton:
    ios:
      US: "//XCUIElementTypeStaticText[@name='Data Sources']"
    android:
      US: "settings_data_sources_item"
  contactUsButton:
    ios:
      US: ""
    android:
      US: "settings_contact_us_item"
  rateTactButton:
    ios:
      US: ""
    android:
      US: "settings_rate_tact_item"
  appVersionLabel:
    ios:
      US: "//*[contains(@name,'3.')]"
    android:
      US: "//*[contains(@text,'2.')]"
  deleteAccountButton:
    ios:
      US: "//XCUIElementTypeStaticText[@name='Delete Account']"
    android:
      US: "settings_account_delete_account_item"
pageTitle:
  US: "page_object"
pageValidators: [
  settingsTitleLabel
]